name: Slack Notification
'on':
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SE_TOOL_REQUESTS_WEBHOOK }}
          SLACK_CHANNEL: general
          SLACK_COLOR: good
          SLACK_ICON: https://a.storyblok.com/f/92909/x/084296103a/logo-blue_140px_rgb.svg
          SLACK_MESSAGE: 'Octolint Issue Created'
          SLACK_TITLE: ${{ github.event.issue.url }}
          SLACK_USERNAME: 'Slack Notification Workflow'
          SLACK_FOOTER: ''
